"""empty message

Revision ID: 0977376016cc
Revises: 
Create Date: 2019-06-21 17:48:40.745230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0977376016cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jhi_authority',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_table('jhi_user',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=191), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('lang_key', sa.String(length=10), nullable=True),
    sa.Column('activation_key', sa.String(length=20), nullable=True),
    sa.Column('reset_key', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('reset_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified_by', sa.String(length=50), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('login')
    )
    op.create_table('jhi_user_autority',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('authority_name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['authority_name'], ['jhi_authority.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['jhi_user.uid'], ),
    sa.PrimaryKeyConstraint('user_id', 'authority_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jhi_user_autority')
    op.drop_table('jhi_user')
    op.drop_table('jhi_authority')
    # ### end Alembic commands ###
